SELECT * FROM classicmodels.`customers`;
SELECT * FROM classicmodels.`customers` WHERE state IS NULL ;
SELECT * FROM classicmodels.`customers` WHERE postalCode LIKE 'N 5804';
SELECT customerName,creditLimit-((creditLimit/10)) FROM classicmodels.`customers`;
SELECT * FROM classicmodels.`customers` WHERE phone LIKE '_7%';
SELECT customerName,creditLimit FROM classicmodels.`customers` WHERE creditLimit BETWEEN 40000 AND 80000;
SELECT customerName,creditLimit,country FROM classicmodels.`customers` WHERE country LIKE 'USA' AND creditLimit>50000;
SELECT customerName,creditLimit,country FROM classicmodels.`customers` WHERE country LIKE 'USA' AND creditLimit BETWEEN 50000 AND 70000;
SELECT customerName,country FROM classicmodels.`customers` WHERE country LIKE 'Germany' OR country LIKE 'UK' OR country LIKE 'Sweden';
SELECT customerName,creditLimit,country FROM classicmodels.`customers` WHERE country IN ('Germany','UK','USA');
SELECT customerNumber,customerName,creditLimit,country FROM classicmodels.`customers` WHERE country IN ('Germany','UK','USA') ORDER BY country ASC,customerName DESC;
SELECT customerNumber,customerName,country FROM classicmodels.`customers` WHERE country LIKE 'Germany' ORDER BY customerNumber DESC;
SELECT SUM(creditLimit) FROM classicmodels.`customers`;
SELECT CONCAT(customerName,'    ',state,'_',country) FROM classicmodels.`customers` ;
SELECT REPLACE(customerName,'a','ZZZZZZZZZ') FROM classicmodels.`customers`;
SELECT REPLACE(customerName,'a',CONCAT('(',customerName,'    ',state,'_',country,')')) FROM classicmodels.`customers`;
SELECT SUBSTRING(customerName,4,5) FROM classicmodels.`customers`;
SELECT customerName,LENGTH(customerName) FROM classicmodels.`customers`;
SELECT customerName,LOWER(customerName) FROM classicmodels.`customers`;
SELECT customerName,ASCII(customerName) FROM classicmodels.`customers`;
SELECT customerName,UPPER(customerName) FROM classicmodels.`customers`;
SELECT MIN(customerNumber),MAX(customerNumber),COUNT(state),AVG(customerNumber),SUM(customerNumber) FROM classicmodels.`customers`;
SELECT country,COUNT(customerNumber) FROM classicmodels.`customers` GROUP BY country ORDER BY COUNT(customerNumber);
SELECT country,COUNT(customerNumber),creditLimit FROM classicmodels.`customers` GROUP BY country  HAVING SUM(creditLimit)>80000;
